version: '3.8'
services:
  pgAdmin:
      image: dpage/pgadmin4
      ports: 
        - 81:80
      environment:
        PGADMIN_DEFAULT_EMAIL: oolaide.dev@gmail.com
        PGADMIN_DEFAULT_PASSWORD: L3mu3lola22.
        PGADMIN_LISTEN_PORT: 80
  app:
    restart: always
    build: .
    ports:
      - 3007:3007
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: uniquepassword # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: fashion_hub
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: