version: '3.8'
services:
  app:
    restart: always
    build: .
    ports:
      - 3008:3008
    env_file: .env
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: uniquepassword # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: fashion_hub
    ports: 
      - 5431:5431
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: